INSERT INTO TEST VALUES(1, 'Hello');
INSERT INTO TEST VALUES(2, 'World');
---the encoded password of 1234
INSERT INTO USER_INFO (ID, USERNAME, PASSWORD) VALUES(1, 'zbdy', '$2a$10$CMelZW7KUVn4wW8nIhD.L.CruIcqLL6GIaDEUXOr9c0RoevZQkAEe');
INSERT INTO USER_INFO (ID, USERNAME, PASSWORD) VALUES(2, 'abcd', '$2a$10$CMelZW7KUVn4wW8nIhD.L.CruIcqLL6GIaDEUXOr9c0RoevZQkAEe');
INSERT INTO BOOK VALUES(1, 'ISIN-123456', 'Spring in Action');
INSERT INTO BOOK VALUES(2, 'ISIN-ABCDEF', 'Docker in Action');