DROP TABLE IF EXISTS TEST;
CREATE TABLE TEST(ID INT PRIMARY KEY,
   NAME VARCHAR(255));

DROP TABLE IF EXISTS USER_INFO;
CREATE TABLE USER_INFO(ID INT PRIMARY KEY,
   USERNAME VARCHAR(255),
   PASSWORD VARCHAR(255));

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(ID INT PRIMARY KEY,
   ISIN VARCHAR(255),
   NAME VARCHAR(255));